CMakeLists.txt, src/complex/Core/Parameters/DataGroupCreationParameter.cpp, src/complex/Core/Parameters/DataGroupCreationParameter.hpp, src/complex/Filter/IParameter.hpp
=> Add DataGroupCreation filter parameter

CMakeLists.txt, src/complex/Filter/Actions/CreateDataGroupAction.cpp, src/complex/Filter/Actions/CreateDataGroupAction.hpp
In support of https://github.com/BlueQuartzSoftware/complex/pull/22
=> Add output Action class CreateDataGroupAction.

CMakeLists.txt, src/complex/Core/Parameters/ArraySelectionParameter.cpp, src/complex/Core/Parameters/ArraySelectionParameter.hpp, src/complex/Filter/DataParameter.hpp
=> Add Parameter to allow selection of a DataArray

src/complex/Filter/IFilter.cpp, src/complex/Filter/Parameters.cpp, src/complex/Filter/Parameters.hpp
=> Parameters: Add method to return comma delimited list of accepted keys

src/complex/DataStructure/DataStructure.cpp, src/complex/DataStructure/DataStructure.hpp, src/complex/Filter/Actions/CreateDataGroupAction.cpp
This method allows a convenient method to generate a nested set of data groups
=> DataStructure: Add makePath() method.

CMakeLists.txt, src/complex/Core/Parameters/DataGroupSelectionParameter.cpp, src/complex/Core/Parameters/DataGroupSelectionParameter.hpp, src/complex/Filter/IParameter.hpp
=> Add DataGroupSelection Filter parameter

CMakeLists.txt, src/complex/Core/Filters/CreateDataGroup.cpp, src/complex/Core/Filters/CreateDataGroup.hpp
This probably depends on PR #21 and PR #22
=> Add Filter CreateDataGroup

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/DeleteData.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/DeleteData.hpp, src/complex/Filter/Actions/DeleteDataAction.cpp, src/complex/Filter/Actions/DeleteDataAction.hpp, src/complex/Parameters/DataPathSelectionParameter.cpp, src/complex/Parameters/DataPathSelectionParameter.hpp
* Added DeleteData filter
* Added DataPathSelectionParameter
* Added DeleteDataAction
=> Added DeleteData Filter

src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportDREAM3DFilter.cpp, src/complex/DataStructure/DataMap.cpp, src/complex/DataStructure/DataStore.hpp, src/complex/DataStructure/DataStructure.cpp, src/complex/DataStructure/DataStructure.hpp, src/complex/Parameters/Dream3dImportParameter.cpp
* Fixed ImportDREAM3DFilter not updating the DataStucture's next ID when importing DataObjects.
* Improved DataStore::deepCopy() performance.
=> Feature/updated import D3D

CMakeLists.txt, src/complex/Pipeline/Messaging/NodeMovedMessage.cpp, src/complex/Pipeline/Messaging/NodeMovedMessage.hpp, src/complex/Pipeline/Pipeline.cpp, src/complex/Pipeline/Pipeline.hpp, test/PipelineTest.cpp
* Added convenience method to Pipeline for moving a node from one index to another.
=> Added Pipeline::Move

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.hpp, src/complex/DataStructure/DataArray.hpp, src/complex/DataStructure/DataPath.cpp, src/complex/DataStructure/DataPath.hpp, src/complex/DataStructure/IDataArray.hpp, src/complex/Parameters/ArrayThresholdsParameter.cpp, src/complex/Parameters/ArrayThresholdsParameter.hpp, src/complex/Utilities/ArrayThreshold.cpp, src/complex/Utilities/ArrayThreshold.hpp
* Added Multi-Threshold Objects filter
*  Added ArrayThresholdsParameter and ArrayThreshold classes.
* Added IDataArray interface for size, tuple, and component count.
=> feature/Multi-Threshold Objects

cmake/Plugin.cmake, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/ComplexCore_test_main.cpp, src/Plugins/ComplexCore/test/CreateDataArrayTest.cpp, src/Plugins/ComplexCore/test/test_dirs.hpp.in
The idea is to figure out the bare basics and use this as a template for other
plugins to use so we can auto generate those tests.
=> Add unit test to ComplexCore Plugin.

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/ConditionalSetValue.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ConditionalSetValue.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CreateDataGroup.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ExampleFilter1.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ExampleFilter2.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ExportDREAM3DFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportDREAM3DFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportTextFilter.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/ConditionalSetValueTest.cpp, src/complex/Common/ComplexConstants.hpp, src/complex/Common/Result.hpp, src/complex/DataStructure/DataArray.hpp, src/complex/DataStructure/IDataStore.hpp, src/complex/Filter/Actions/CreateArrayAction.cpp, src/complex/Filter/Arguments.hpp, src/complex/Utilities/DataArrayUtilities.hpp, src/complex/Utilities/Parsing/HDF5/H5FileWriter.cpp, src/complex/Utilities/Parsing/HDF5/H5FileWriter.hpp, src/complex/Utilities/TemplateHelpers.hpp, test/CMakeLists.txt, test/DREAM3DFileTest.cpp, test/H5Test.cpp, test/UnitTestCommon.hpp
=> FILTER: Add ConditionalSetValue Filter

src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/RobustAutomaticThreshold.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RobustAutomaticThreshold.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/ConditionalSetValueTest.cpp, src/Plugins/ComplexCore/test/RobustAutomaticThresholdTest.cpp, src/complex/DataStructure/DataStructure.cpp, src/complex/DataStructure/DataStructure.hpp
* Added RobustAutomaticThreshold filter
=> Added RobustAutomaticThreshold Filter

src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/FindSizes.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/FindSizes.hpp
=> Added FindSizes filter

CMakeLists.txt, src/PipelineRunner/CMakeLists.txt, src/PipelineRunner/src/PRObserver.cpp, src/PipelineRunner/src/PRObserver.hpp, src/PipelineRunner/src/PipelineRunner.cpp, src/complex/Pipeline/Messaging/AbstractPipelineMessage.hpp, src/complex/Pipeline/Messaging/FilterPreflightMessage.cpp, src/complex/Pipeline/Messaging/FilterPreflightMessage.hpp, src/complex/Pipeline/Messaging/NodeAddedMessage.cpp, src/complex/Pipeline/Messaging/NodeAddedMessage.hpp, src/complex/Pipeline/Messaging/NodeMovedMessage.cpp, src/complex/Pipeline/Messaging/NodeMovedMessage.hpp, src/complex/Pipeline/Messaging/NodeRemovedMessage.cpp, src/complex/Pipeline/Messaging/NodeRemovedMessage.hpp, src/complex/Pipeline/Messaging/NodeStatusMessage.cpp, src/complex/Pipeline/Messaging/NodeStatusMessage.hpp, src/complex/Pipeline/Messaging/PipelineFilterMessage.cpp, src/complex/Pipeline/Messaging/PipelineFilterMessage.hpp, src/complex/Pipeline/Messaging/PipelineNodeMessage.cpp, src/complex/Pipeline/Messaging/PipelineNodeMessage.hpp, src/complex/Pipeline/Messaging/RenamedMessage.cpp, src/complex/Pipeline/Messaging/RenamedMessage.hpp, src/complex/Pipeline/Pipeline.cpp, src/complex/Pipeline/Pipeline.hpp
* PipelineRunner executable takes the target filepath as an argument.
* Added toString() method to PipelineNodeMessages.
* Added PipelineNodeMessage to pass FilterNode messages through the parent pipeline.
=> Added PipelineRunner executable

src/complex/DataStructure/DataObject.cpp, src/complex/Pipeline/AbstractPipelineNode.cpp, src/complex/Pipeline/AbstractPipelineNode.hpp, src/complex/Pipeline/PipelineFilter.cpp
Pipeline errors no longer clear the DataStructure.
=> Save Filter DataStructure on Error

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/InterpolatePointCloudToRegularGridFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp, src/complex/DataStructure/DataMap.cpp, src/complex/Utilities/FilterUtilities.hpp, test/UnitTestCommon/include/complex/UnitTest/UnitTestCommon.hpp
* Fixed bug in DataMap that cleared the DataStructure in DataObjects.
=> Added RemoveFlaggedVertices filter

src/complex/DataStructure/DataPath.cpp, test/DataStructTest.cpp
=> Now allow empty string to become empty DataPath in FromString

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/RenameDataGroup.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RenameDataGroup.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/RenameDataGroupTest.cpp, src/complex/Filter/Actions/RenameDataAction.cpp, src/complex/Filter/Actions/RenameDataAction.hpp
* Added RenameDataGroup filter
* Added RenameDataAction
=> Added RenameDataGroup

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/CopyDataGroup.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CopyDataGroup.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/CopyDataGroupTest.cpp, src/complex/Filter/Actions/CopyGroupAction.cpp, src/complex/Filter/Actions/CopyGroupAction.hpp
* Added CopyDataGroup filter
* Added CopyGroupAction
=> Added CopyDataGroup

src/Plugins/TestOne/src/TestOne/Filters/ExampleFilter2.cpp
=> Fix DynamicTableParameter in Example Filter 2 to correct headers &

src/complex/Common/Types.hpp, src/complex/Pipeline/AbstractPipelineNode.hpp
=> Move some enums out of AbstractPipelineNode into Types.hpp

src/Plugins/ComplexCore/src/ComplexCore/Filters/CalculateTriangleAreasFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/IdentifySample.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/LaplacianSmoothingFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp, src/Plugins/TestOne/src/TestOne/Filters/ExampleFilter2.cpp, src/complex/DataStructure/Geometry/AbstractGeometry.hpp, src/complex/DataStructure/Geometry/EdgeGeom.cpp, src/complex/DataStructure/Geometry/EdgeGeom.hpp, src/complex/DataStructure/Geometry/HexahedralGeom.cpp, src/complex/DataStructure/Geometry/HexahedralGeom.hpp, src/complex/DataStructure/Geometry/ImageGeom.cpp, src/complex/DataStructure/Geometry/ImageGeom.hpp, src/complex/DataStructure/Geometry/QuadGeom.cpp, src/complex/DataStructure/Geometry/QuadGeom.hpp, src/complex/DataStructure/Geometry/RectGridGeom.cpp, src/complex/DataStructure/Geometry/RectGridGeom.hpp, src/complex/DataStructure/Geometry/TetrahedralGeom.cpp, src/complex/DataStructure/Geometry/TetrahedralGeom.hpp, src/complex/DataStructure/Geometry/TriangleGeom.cpp, src/complex/DataStructure/Geometry/TriangleGeom.hpp, src/complex/DataStructure/Geometry/VertexGeom.cpp, src/complex/DataStructure/Geometry/VertexGeom.hpp, src/complex/Parameters/GeometrySelectionParameter.cpp, src/complex/Parameters/GeometrySelectionParameter.hpp
* Added pure virtual function AbstractGeometry::getGeomType()
=> Changed GeometrySelectionParameter to use AbstractGeometry::Type

src/Plugins/ComplexCore/src/ComplexCore/Filters/ConditionalSetValue.cpp, src/Plugins/ComplexCore/test/ConditionalSetValueTest.cpp
Update unit test to include UInt8 and Int8 Input arrays.
=> ConditionalSetValue: Allow use of Bool, UInt8, Int8 as the mask array

src/Plugins/ComplexCore/src/ComplexCore/Filters/ConditionalSetValue.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp, src/Plugins/ComplexCore/test/ConditionalSetValueTest.cpp, src/Plugins/ComplexCore/test/FindNeighborListStatisticsTest.cpp, src/Plugins/ComplexCore/test/InterpolatePointCloudToRegularGridTest.cpp, src/Plugins/ComplexCore/test/MapPointCloudToRegularGridTest.cpp, src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp, src/complex/Utilities/DataArrayUtilities.cpp, src/complex/Utilities/DataArrayUtilities.hpp, test/UnitTestCommon/include/complex/UnitTest/UnitTestCommon.hpp
RemoveFlaggedVertices: Check the ending Vertex Array size to make sure it is correct.
ConditionalSetValue: Fix bug where we created a secondary conditional bool array without realizing it.
=> Various Filter Unit Test Cleanups

src/complex/Parameters/MultiArraySelectionParameter.cpp
* Also now accumulate errors for all paths and return them instead
of just the first one
=> Fixed not checking if the selected path is a DataArray

src/complex/DataStructure/Metadata.cpp, src/complex/DataStructure/Metadata.hpp
=> Add a 'contains' method to Metadata() class.

src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportTextFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/LinkGeometryDataFilter.cpp, src/complex/Common/ComplexConstants.hpp
ImportTextFilter and LinkGeometryDataFilter
=> Help Text and Human Label updates to several filters

src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveMinimumSizeFeaturesFilter.cpp
=> MinSizeFeatures should take int32 for the feature ids

src/complex/DataStructure/BaseGroup.hpp, test/DataStructTest.cpp
* Added to DataStructure unit tests
=> Added BaseGroup::findAllChildrenOfType utility method

vcpkg-configuration.json, vcpkg.json
* Primarily used for the plugin ITKImageProcessing
=> Added itk as optional vcpkg feature (not required by default)

src/complex/Parameters/FileSystemPathParameter.cpp
=> FileSystemPathPararameter: Update error messages

src/complex/Filter/IParameter.hpp, src/complex/Parameters/ChoicesParameter.cpp, test/UnitTestCommon/include/complex/UnitTest/UnitTestCommon.hpp
=> Update Choices parameter error text

src/Plugins/ComplexCore/test/FindFeaturePhasesFilterTest.cpp
* Move createDataStructure method into unnamed namespace.
* Use blank data structure.
=> FindFeaturePhases test tweaks

src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/QuickSurfaceMesh.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/QuickSurfaceMesh.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/QuickSurfaceMeshFilter.cpp, src/Plugins/ComplexCore/test/QuickSurfaceMeshFilterTest.cpp
=> Use DataGroupCreation Parameter for the created Triangle Geometry

src/complex/Utilities/DataArrayUtilities.hpp, test/UnitTestCommon/include/complex/UnitTest/UnitTestCommon.hpp
=> Add more constants and more verbose error message on binary file import

vcpkg.json
=> Add EBSDLib to list of dependencies in vcpkg.json.

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/docs/CropImageGeometry.md, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/CropImageGeomTest.cpp, src/complex/Utilities/SamplingUtils.hpp
* Added CropImageGeometry filter
* Added SamplingUtils
=> FILTER: Crop Image Geometry

src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighborListStatistics.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/InterpolatePointCloudToRegularGridFilter.cpp, src/complex/DataStructure/INeighborList.cpp, src/complex/DataStructure/INeighborList.hpp, src/complex/DataStructure/NeighborList.cpp, src/complex/DataStructure/NeighborList.hpp, src/complex/Parameters/ArraySelectionParameter.cpp
* Updated INeighborList to use DataObject as its base class instead of IDataArray.
* Updated parameters and filters to compile and pass tests.
=> Changed INeighborList base class

src/complex/Utilities/Parsing/DREAM3D/Dream3dIO.cpp
=> BUG FIX: Legacy D3D array dimensions are now read correctly.

src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/AlignGeometries.hpp, src/Plugins/ComplexCore/test/AlignGeometriesTest.cpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/complex/DataStructure/Geometry/RectGridGeom.cpp, src/complex/DataStructure/Geometry/RectGridGeom.hpp
* Added AlignGeometries filter
=> FILTER: Align Geometries

CMakeLists.txt, src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/SetOriginResolutionImageGeom.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/SetOriginResolutionImageGeom.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/SetOriginResolutionImageGeomTest.cpp, src/complex/Filter/Actions/UpdateImageGeomAction.cpp, src/complex/Filter/Actions/UpdateImageGeomAction.hpp
* Added SetOriginResolutionImageGeom filter
=> FILTER: SetOriginResolutionImageGeom

src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/docs/ChangeAngleRepresentation.md, src/Plugins/ComplexCore/src/ComplexCore/Filters/ChangeAngleRepresentation.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ChangeAngleRepresentation.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/ChangeAngleRepresentationTest.cpp, src/complex/Common/ComplexRange.hpp
Filter converts angles from Degrees to Radians and vice versa
=> FILTER: Add ChangeAngleRepresentation filter.

src/complex/Pipeline/Pipeline.cpp
By placing the check after the filter comes back from executing the signal
that the pipeline is canceled will actually be emitted. Since the filters
take much longer to execute than the basic bits of the pipeline loop the
opportunity to emit the cancel signal was always missed.
=> Place cancel check _after_ filter returns from execute.

src/Plugins/ComplexCore/src/ComplexCore/Filters/FindSurfaceFeatures.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RobustAutomaticThreshold.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ScalarSegmentFeaturesFilter.cpp, src/Plugins/ComplexCore/test/FindSurfaceFeaturesTest.cpp, src/Plugins/ComplexCore/test/RobustAutomaticThresholdTest.cpp
=> MultiThresholdObjects: Create BoolArray instead of UInt8Array

src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/data/MinNeighbors.md, src/Plugins/ComplexCore/src/ComplexCore/Filters/MinNeighbors.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/MinNeighbors.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/MinNeighborsTest.cpp
=> Added MinNeighbors filter

src/Plugins/ComplexCore/docs/ExtractInternalSurfacesFromTriangleGeometry.md, src/Plugins/ComplexCore/src/ComplexCore/Filters/ExtractInternalSurfacesFromTriangleGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/QuickSurfaceMeshFilter.cpp, src/Plugins/ComplexCore/test/ExtractInternalSurfacesFromTriangleGeometryTest.cpp, src/complex/Filter/Actions/CreateTriangleGeomAction.cpp, src/complex/Filter/Actions/CreateTriangleGeomAction.hpp
=> ExtractInternalSurfacesFromTriangleGeometry: Rewrote algorithm without hashes and maps for a large speed up and memory reduction

src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/ScalarSegmentFeatures.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/ScalarSegmentFeatures.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ScalarSegmentFeaturesFilter.cpp
=> ScalarSegmentFeatures: Fix crashing due to casting from uint8 to bool

src/complex/DataStructure/Geometry/AbstractGeometry2D.cpp, src/complex/DataStructure/Geometry/AbstractGeometry2D.hpp, src/complex/DataStructure/Geometry/AbstractGeometry3D.cpp, src/complex/DataStructure/Geometry/AbstractGeometry3D.hpp, src/complex/DataStructure/Geometry/EdgeGeom.cpp, src/complex/DataStructure/Geometry/EdgeGeom.hpp
to AbstractGeometry3D & EdgeGeom
=> Add getter for the DataObject ID for vertices array 

src/complex/DataStructure/Geometry/EdgeGeom.cpp, src/complex/DataStructure/Geometry/EdgeGeom.hpp
* Made EdgeGeom::getVertsAtEdge const
* Added static constant k_NumVerts to EdgeGeom
=> Minor EdgeGeom changes

.gitignore
* That line prevented new files from being added to existing docs folders
=> Removed "docs" from gitignore

src/Plugins/TestOne/CMakeLists.txt, src/Plugins/TestOne/src/TestOne/Filters/DynamicTableExample.cpp, src/Plugins/TestOne/src/TestOne/Filters/DynamicTableExample.hpp
This filter show all 4 combinations of dynamic and fixed rows/columns
=> Add DynamicTableExample test filter.

src/complex/DataStructure/DataStructure.cpp, src/complex/DataStructure/DataStructure.hpp
=> Add helper method that returns all data object ids in the data structure.

src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/IterativeClosestPointFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/QuickSurfaceMeshFilter.cpp, src/complex/Utilities/Parsing/DREAM3D/Dream3dIO.cpp
* Fixed legacy geometry reading
* Fixed CropImageGeometry preflight
* Disabled triple lines in QuickSurfaceMesh
* Improved speed of IterativeClosestPoint
* Enabled messages in IterativeClosestPoint
=> CT pipeline fixes

src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropVertexGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/IterativeClosestPointFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/SetImageGeomOriginScalingFilter.cpp, test/PipelineTest.cpp
Both logic errors and performance fixes were put in place.
=> Final Fixes to allow PacMan Sample Pipelines to generate matching result

cmake/Utility.cmake, src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/LaplacianSmoothing.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/InterpolatePointCloudToRegularGridFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/MapPointCloudToRegularGridFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/MultiThresholdObjects.cpp, src/Plugins/ComplexCore/test/MinNeighborsTest.cpp, src/Plugins/ComplexCore/test/PointSampleTriangleGeometryFilterTest.cpp, src/complex/DataStructure/Observers/AbstractDataStructureObserver.cpp, src/complex/Parameters/VectorParameter.cpp, src/complex/Pipeline/Messaging/PipelineNodeObserver.cpp, src/complex/Utilities/GeometryHelpers.hpp
* Enables C4456, C4457, C4458, and C4459 as errors for msvc
* Enables shadow as error for gcc/clang
=> Enabled compile error for name shadowing

src/complex/Parameters/FileSystemPathParameter.cpp, src/complex/Utilities/StringUtilities.hpp
=> Ensure file extensions are always compared as lower case strings.

src/complex/DataStructure/AbstractDataStore.hpp, test/DataArrayTest.cpp
* Added methods to set tuple values.
* Added methods to set a specific component value.
* Added method to get a specific component value.
=> Added tuple and component methods to AbstractDataStore

src/complex/Parameters/GeneratedFileListParameter.cpp
Allow GeneratedFileListParameter to import a single file
=> Allow start index to be equal to end index

test/UnitTestCommon/include/complex/UnitTest/UnitTestCommon.hpp
Signed-off-by: bpennie <braden.pennie@bluequartz.net>
=> added default argument to CreateTestDataArray

src/Plugins/TestOne/src/TestOne/Filters/ExampleFilter1.cpp, src/complex/Parameters/FileSystemPathParameter.cpp, src/complex/Parameters/FileSystemPathParameter.hpp
edited argument/variable names and added accessor to "acceptAllExtensions" to allow a FileSystemPath to accept all extensions
=> Updated FileSystemPathParameter to accept all extensions

CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportTextFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportTextFilter.hpp, src/Plugins/ComplexCore/test/ScalarSegmentFeaturesFilterTest.cpp, src/complex/Utilities/AlignSections.cpp, src/complex/Utilities/AlignSections.hpp, src/complex/Utilities/DataArrayUtilities.cpp, src/complex/Utilities/DataArrayUtilities.hpp, src/complex/Utilities/SamplingUtils.hpp, src/complex/Utilities/SegmentFeatures.cpp, src/complex/Utilities/TBBTaskRunner.hpp
* CropImageGeometry: Parallelize the array copying
* Segment Features: Add ability to cancel the segmentation loop. Clean up test code
* DataArrayUtilities: Added functions to support using Bool or UInt8 for Mask Arrays
* Create base class for AlignSections Algorithm.
=> Various API additions to support filter development

src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportHDF5Dataset.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportHDF5Dataset.hpp, src/Plugins/ComplexCore/test/ImportHDF5DatasetTest.cpp, src/complex/Parameters/ImportHDF5DatasetParameter.cpp, src/complex/Parameters/ImportHDF5DatasetParameter.hpp
Removed the DataGroupSelectionParameter from the ImportHDF5Dataset filter and added an optional parent DataPath data member to the ImportHDF5DatasetParameter ValueType instead
=> Move Import HDF5 parent group selection to ImportHDF5DatasetParameter

src/complex/DataStructure/DataArray.hpp, test/DataArrayTest.cpp
=> Fix bug in CopyTuple and added unit test

src/Plugins/ComplexCore/CMakeLists.txt, src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/FindArrayStatistics.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/FindArrayStatistics.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/FindArrayStatisticsFilter.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/FindArrayStatisticsFilter.hpp, src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/FindArrayStatisticsTest.cpp, src/Plugins/ComplexCore/test/test_dirs.hpp.in, src/complex/Utilities/Math/StatisticsCalculations.hpp
The "Compute per feature/ensemble id" option is implemented to the extent possible but turned off/disabled for the user at the moment until we get the AttributeMatrix back.
=> FindArrayStatisticsFilter 

vcpkg-configuration.json
=> Update to latest complex-registry to pick up EbsdLib 1.0.14

vcpkg-configuration.json
=> Update complex-registry baseline git commit

cmake/Utility.cmake
=> Ensure all cases of shadowed variables are picked up.

src/complex/Utilities/DataGroupUtilities.cpp, src/complex/Utilities/DataGroupUtilities.hpp
=> DataGroupUtilities: Add function to return vector<IDataArray> of specific DataArrays

src/complex/Parameters/FileSystemPathParameter.cpp
=> fixed bug in filepathparameters

src/Plugins/ComplexCore/src/ComplexCore/ComplexCorePlugin.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ApplyTransformationToGeometryFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ChangeAngleRepresentation.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropImageGeometry.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/CropVertexGeometry.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ExtractInternalSurfacesFromTriangleGeometry.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/FindArrayStatisticsFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/FindFeaturePhasesFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/IdentifySample.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportHDF5Dataset.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/InitializeData.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/InterpolatePointCloudToRegularGridFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/IterativeClosestPointFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/LaplacianSmoothingFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/MapPointCloudToRegularGridFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/QuickSurfaceMeshFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/RawBinaryReaderFilter.hpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ScalarSegmentFeaturesFilter.hpp
Updated Complex UUIDs to make them all unique with UUID v4
=> Updated UUIDs to make all of them unique using UUID v4

src/Plugins/ComplexCore/src/ComplexCore/Filters/IdentifySample.cpp, src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportHDF5Dataset.cpp, src/Plugins/ComplexCore/test/ImportHDF5DatasetTest.cpp, src/complex/DataStructure/AbstractDataStore.hpp, src/complex/DataStructure/Montage/AbstractTileIndex.cpp, src/complex/DataStructure/NeighborList.cpp, src/complex/Parameters/util/DynamicTableData.cpp, src/complex/Utilities/ArrayThreshold.cpp, src/complex/Utilities/ArrayThreshold.hpp, src/complex/Utilities/TooltipRowItem.cpp
* Default member initialization
* Range based loops from C++11
=> Clang Tidy Cleanup [range-based loops, member initialization]

src/complex/DataStructure/Geometry/AbstractGeometryGrid.hpp, src/complex/DataStructure/Geometry/ImageGeom.cpp, src/complex/DataStructure/Geometry/ImageGeom.hpp, src/complex/DataStructure/Geometry/RectGridGeom.cpp, src/complex/DataStructure/Geometry/RectGridGeom.hpp
=> Update ImageGeom getIndex method with correct algorithm.

src/Plugins/ComplexCore/test/CMakeLists.txt, src/Plugins/ComplexCore/test/ImageGeomTest.cpp, src/complex/DataStructure/Geometry/ImageGeom.cpp
Final ImageGeom::getIndex correction, with a unit test to prove that it works.
=> Correcting ImageGeom::getIndex method and including unit test.
