vcpkg-configuration.json

* [complex-registry](https://github.com/BlueQuartzSoftware/complex-registry) gives us control over how our dependencies are
built
* At the moment the packages are largely the same as the vcpkg
versions except for the removal of pkg-config support. This removes
the implicit pkg-config dependency for ports that used the function
`vcpkg_fixup_pkgconfig`

Add complex-registry as vcpkg registry

---

CMakeLists.txt
scripts/filter.cpp.in
src/complex/Common/StringLiteral.hpp
src/complex/Core/Filters/CreateDataArray.cpp
src/complex/Core/Filters/CreateDataArray.hpp
src/complex/Core/Filters/ImportTextFilter.cpp
src/complex/Core/Filters/TestFilter1.cpp
src/complex/Core/Filters/TestFilter2.cpp
src/complex/Core/Parameters/FileSystemPathParameter.cpp
src/complex/Core/Parameters/GeneratedFileListParameter.cpp
src/complex/Filter/Arguments.cpp
src/complex/Filter/Arguments.hpp
src/complex/Filter/FilterTraits.hpp
src/complex/Filter/ParameterTraits.hpp
src/complex/Filter/Parameters.cpp
src/complex/Filter/Parameters.hpp
test/ArgumentsTest.cpp
test/CoreFilterTest.cpp
test/FilePathGeneratorTest.cpp
test/Plugin/Test2Filter.cpp
test/Plugin/TestFilter.cpp
test/UuidTest.cpp
test/complex_test_dirs.h.in

* Allows easy access to size of a literal
* Replaced uses of `static inline constexpr const char*` with `static inline constexpr StringLiteral`

Added `StringLiteral` type

---

src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportDREAM3DFilter.cpp
src/complex/Parameters/Dream3dImportParameter.cpp
src/complex/Parameters/Dream3dImportParameter.hpp

* Changed ImportData.DataPaths to std::optional. std::nullopt signifies that all data should be imported. An empty vector is not an expected value and requires feedback for the user.
* Updated ImportDREAM3DFilter accordingly.

Updated ImportDREAM3DFilter with std::optional paths

---

src/Plugins/ComplexCore/CMakeLists.txt
src/Plugins/ComplexCore/docs/RawBinaryReader.md
src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/RawBinaryReader.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/Algorithms/RawBinaryReader.hpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/RawBinaryReaderFilter.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/RawBinaryReaderFilter.hpp
src/Plugins/ComplexCore/test/CMakeLists.txt
src/Plugins/ComplexCore/test/RawBinaryReaderTest.cpp
src/complex/Common/Bit.hpp
src/complex/Common/TypesUtility.hpp
src/complex/DataStructure/DataArray.hpp

* Ported RawBinaryReader filter from DREAM.3D to DREAM.3D-NX.  Added a helper class for the actual RawBinaryReader algorithm.
* Included a unit test and documentation.
* Updated Bit.hpp to include bit swapping for 32-bit and 64-bit floating point values.
* Updated DataArray.hpp to bitswap all elements in a DataArray.
* These bit-swapping API changes are needed for the RawBinaryReader filter.

Adding Raw Binary Reader Filter

---

src/complex/Pipeline/AbstractPipelineNode.cpp
src/complex/Pipeline/AbstractPipelineNode.hpp
src/complex/Pipeline/Messaging/NodeStatusMessage.cpp
src/complex/Pipeline/Pipeline.cpp
src/complex/Pipeline/Pipeline.hpp
src/complex/Pipeline/PipelineFilter.cpp
src/complex/Pipeline/PipelineFilter.hpp

* Status has been updated to be used as flags instead of single values.
* Convenience methods added to AbstractPipelineNode to check for each of the flags.
* Updated Pipeline and PipelineFilter to take advantage of node Status changes.
* Updated NodeStatusMessage.toString()
* Pipeline no longer accepts index arguments as const references.

Updated AbstractPipelineNode::Status values

---

src/Plugins/ComplexCore/src/ComplexCore/Filters/ExampleFilter1.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/ExportDREAM3DFilter.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportTextFilter.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/RawBinaryReaderFilter.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/StlFileReaderFilter.cpp
src/complex/Parameters/FileSystemPathParameter.cpp
src/complex/Parameters/FileSystemPathParameter.hpp

Can now explicitly specify a list of all valid file extension types for Input/Output file path types or leave blank to allow any extensions.

Add support for multiple valid file extensions in FileSystemPathParameter

---

src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp
src/complex/DataStructure/BaseGroup.cpp
src/complex/DataStructure/BaseGroup.hpp
src/complex/DataStructure/DataMap.cpp
src/complex/DataStructure/DataMap.hpp
src/complex/DataStructure/DataObject.cpp
src/complex/DataStructure/DataObject.hpp
src/complex/DataStructure/DataStructure.cpp
src/complex/DataStructure/Messaging/DataAddedMessage.cpp

Empty is convenient to use and is STL compliant
DataObject::getParentDataPaths is more descriptive and is not ambiguous concerning what is returned.

DataObject::getParentDataPaths() and BaseGroup::empty()

---

src/complex/DataStructure/BaseGroup.cpp
src/complex/DataStructure/DataStructure.cpp
test/DataStructTest.cpp

When creating a new `DataObject` and trying to insert into `BaseGroup`, the id is generated before the insertion. Then in `BaseGroup::canInsert(const DataObject*)`, it calls `BaseGroup::contains(const DataObject*)` which checks if the id of the `DataObject` already exists in the group. But since the id was just generated it will never be in the group and `contains` will always return `false`. So objects with the same name will exist in the group which will cause an issue when using a `DataPath` to attempt to access them.

Fixed issue when trying to insert objects with duplicate names

---

CMakeLists.txt
src/complex/DataStructure/DataPath.cpp
src/complex/DataStructure/DataPath.hpp
src/complex/Filter/Actions/CopyArrayInstanceAction.cpp
src/complex/Filter/Actions/CopyArrayInstanceAction.hpp
src/complex/Filter/Actions/CreateArrayAction.cpp
src/complex/Filter/Actions/CreateArrayAction.hpp
src/complex/Filter/Actions/CreateDataGroupAction.cpp
src/complex/Filter/Actions/CreateDataGroupAction.hpp
src/complex/Filter/Actions/CreateGeometry2DAction.hpp
src/complex/Filter/Actions/CreateImageGeometryAction.cpp
src/complex/Filter/Actions/CreateImageGeometryAction.hpp
src/complex/Filter/Actions/CreateNeighborListAction.cpp
src/complex/Filter/Actions/CreateNeighborListAction.hpp
src/complex/Filter/Actions/CreateVertexGeometryAction.hpp
src/complex/Filter/Actions/ImportObjectAction.cpp
src/complex/Filter/Actions/ImportObjectAction.hpp
src/complex/Filter/Output.hpp
src/complex/Pipeline/AbstractPipelineNode.cpp
src/complex/Pipeline/AbstractPipelineNode.hpp
src/complex/Pipeline/Messaging/OutputRenamedMessage.cpp
src/complex/Pipeline/Messaging/OutputRenamedMessage.hpp
src/complex/Pipeline/Pipeline.cpp
src/complex/Pipeline/Pipeline.hpp
src/complex/Pipeline/PipelineFilter.cpp
src/complex/Pipeline/PipelineFilter.hpp
test/PipelineTest.cpp

* PipelineFilter now checks for renamed outputs between preflights. A signal is emitted when the change in arguments results in a created DataObject having a different DataPath.
* Added IDataCreationAction as a subclass of IDataAction specific for the creation of DataObjects in the DataStructure.
* Pipelines adjust the arguments of PipelineFilter nodes following a renamed DataPath creation.
* Added a renamed output test to PipelineTest.cpp

Added Output DataPath rename checks

---

CMakeLists.txt
src/Plugins/ComplexCore/CMakeLists.txt
src/Plugins/ComplexCore/src/ComplexCore/Filters/CreateDataArray.hpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/ExtractInternalSurfacesFromTriangleGeometry.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/ExtractInternalSurfacesFromTriangleGeometry.hpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp
src/Plugins/ComplexCore/test/CMakeLists.txt
src/Plugins/ComplexCore/test/ExtractInternalSurfacesFromTriangleGeometryTest.cpp
src/complex/DataStructure/DataArray.hpp
src/complex/DataStructure/DataObject.cpp
src/complex/DataStructure/DataObject.hpp
src/complex/DataStructure/DataStructure.cpp
src/complex/DataStructure/Geometry/AbstractGeometry2D.cpp
src/complex/DataStructure/Geometry/TriangleGeom.cpp
src/complex/DataStructure/Messaging/DataAddedMessage.cpp
src/complex/Filter/Actions/CreateTriangleGeomAction.cpp
src/complex/Filter/Actions/CreateTriangleGeomAction.hpp

* Added ExtractInternalSurvacesFromTriangleGeom filter
* Added CreateTriangleGeomAction
* Renamed DataObject::getParentDataPaths to getDataPaths due to misleading name. DataObject::getParentDataPaths did not return DataPaths to known parents. It returned the DataPaths to the object calling it.

FILTER: ExtractInternalSurfacesFromTriangleGeometry

---

src/Plugins/ComplexCore/src/ComplexCore/Filters/FindDifferencesMap.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/FindNeighborListStatistics.cpp
src/complex/Common/Types.hpp
src/complex/Common/TypesUtility.hpp
src/complex/DataStructure/AbstractDataStore.cpp
src/complex/DataStructure/IDataArray.hpp
src/complex/DataStructure/NeighborList.cpp
src/complex/Utilities/DataArrayUtilities.cpp

* Used to be for NeighborList when it inherited from IDataArray

Removed DataType::error since it is no longer used

---

src/complex/Pipeline/Pipeline.hpp
src/complex/Pipeline/PipelineFilter.cpp

This PR does the following:
* Sets the name of a pipeline to "Untitled Pipeline" to match the GUI and general UI expectations
* Generates an error message that also includes the name of the filter that cannot be loaded based off the given UUID in the JSON file.

Adding more details to error message when loading pipeline fails

---

src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp
src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp
src/complex/DataStructure/Geometry/VertexGeom.cpp
src/complex/DataStructure/Geometry/VertexGeom.hpp
src/complex/Utilities/Parsing/DREAM3D/Dream3dIO.cpp

* Import shared vertex, edge, triangle, quad, hexahedral, and tetrahedral arrays.
* Imported node arrays do not link to any existing DataArrays.

Update legacy import of node-based geometries

---

src/complex/DataStructure/DataStore.hpp

Also eliminates the need to copy the data manually in the deepCopy() function.

DataStore: Use memcpy for copy constructor.

---

src/PipelineRunner/src/PRObserver.cpp
src/PipelineRunner/src/PRObserver.hpp
src/PipelineRunner/src/PipelineRunner.cpp

* Added preflight using `-p` or `--preflight` as argv[2] argument.
* Printing basic begin / end pipeline messaging to console. Filters are not included in the messaging changes.

Added Preflight to PipelineRunner

---

src/complex/Utilities/Parsing/DREAM3D/Dream3dIO.cpp

* Legacy array dimensions were reversed
* The incorrect type was used in a `std::accumulate` call when calculating the number tuples from the dimensions of a legacy `NeighborList`

Fixed bugs while reading in legacy array dimensions

---

cmake/Plugin.cmake
src/Plugins/ComplexCore/src/ComplexCore/Filters/ExtractInternalSurfacesFromTriangleGeometry.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/LinkGeometryDataFilter.cpp
src/complex/Filter/Actions/CreateTriangleGeomAction.cpp
src/complex/Filter/Actions/CreateTriangleGeomAction.hpp

This helps the data structure be a bit more familiar to those coming from SIMPL.
Minor filter parameters organization for ExtractInternalSrufacesFromTriangleGeometry
and LinkGeometryDataFilter.

Update Default names of Triangle and Vertex Arrays in Triangle Geometry and fix plugin unit test

---

src/complex/Filter/Actions/DeleteDataAction.cpp

Delete Data filter no longer crashes when deleting top-level item.

---

src/complex/DataStructure/Geometry/AbstractGeometry2D.cpp
src/complex/DataStructure/Geometry/AbstractGeometry2D.hpp
src/complex/DataStructure/Geometry/AbstractGeometry3D.cpp
src/complex/DataStructure/Geometry/AbstractGeometry3D.hpp
src/complex/DataStructure/Geometry/EdgeGeom.cpp
src/complex/DataStructure/Geometry/EdgeGeom.hpp
src/complex/DataStructure/Geometry/HexahedralGeom.cpp
src/complex/DataStructure/Geometry/QuadGeom.cpp
src/complex/DataStructure/Geometry/QuadGeom.hpp
src/complex/DataStructure/Geometry/TetrahedralGeom.cpp
src/complex/DataStructure/Geometry/TriangleGeom.cpp
src/complex/DataStructure/Geometry/TriangleGeom.hpp
test/H5Test.cpp

* Added missing geometry array ID reading from HDF5 files.
* Added `get[*]Id() const` methods for geometry array getters that return the DataObject::IdType as an optional without requiring a DataStructure.
* Updated HDF5 unit test to check vertex, edge, triangle, and quad geometry values.

Updated geometry readHdf5 methods

---

src/Plugins/ComplexCore/src/ComplexCore/Filters/ImportDREAM3DFilter.cpp

* Previously it would read all the data in the dream3d file which would never be used

Fixed ImportDREAM3DFilter::toJson to only read pipeline from file

---

src/complex/DataStructure/DataGroup.cpp
src/complex/DataStructure/Geometry/EdgeGeom.cpp
src/complex/DataStructure/Geometry/HexahedralGeom.cpp
src/complex/DataStructure/Geometry/ImageGeom.cpp
src/complex/DataStructure/Geometry/QuadGeom.cpp
src/complex/DataStructure/Geometry/RectGridGeom.cpp
src/complex/DataStructure/Geometry/TetrahedralGeom.cpp
src/complex/DataStructure/Geometry/TriangleGeom.cpp
src/complex/DataStructure/Geometry/VertexGeom.cpp
src/complex/DataStructure/Montage/GridMontage.cpp

* Not all information was copied previously (e.g. TriangleGeom didn't copy the vertices id)

Fixed deepCopy() for DataGroup, geometries, and montage

---

src/Plugins/TestOne/src/TestOne/Filters/ExampleFilter2.cpp
src/complex/Filter/Parameters.cpp
src/complex/Filter/Parameters.hpp

This allows the gui side to get the specific value of a linked parameter that
would make the target parameter 'active'
Also update ExampleFilter2 to use linked parameters.

Parameters: Add API to retrieve the active value for a linked parameter.

---

src/complex/Utilities/Parsing/DREAM3D/Dream3dIO.cpp

Cuts down on spurious HDF5 warnings.

Add a check for the existence of the file before trying to open it.

---

src/complex/Common/RgbColor.cpp
src/complex/Common/RgbColor.hpp

All of the legacy SIMPL codes assume ARGB color layout. Nothing else uses the RGB in complex at this time so we can safely just switch over to how it was done in the past.

Correct ARGB calculations to use ARGB and not RGBA

---

src/Plugins/TestOne/src/TestOne/Filters/ErrorWarningFilter.cpp
src/Plugins/TestOne/src/TestOne/Filters/ErrorWarningFilter.hpp

Adds parameters to the ErrorWarningFilter in TestOne plugin to test the handling of runtime exceptions during pipeline preflight and execution

Intentional preflight & execute exception parameters

---

src/complex/DataStructure/DataStore.hpp
src/complex/DataStructure/EmptyDataStore.hpp

Methods in tight loops end up calling getNumberOfTuples() repeatedly which calculates
the same value over and over. Update the number of tuples, number of components
and size when the tuple shape is changed.
In one instance this gave a 3X speed up.

Cache the number of tuples, number of components and size.

---

src/complex/DataStructure/DataStore.hpp
src/complex/DataStructure/Factory/DataArrayFactory.hpp
src/complex/Utilities/Parsing/HDF5/H5DatasetReader.cpp
src/complex/Utilities/Parsing/HDF5/H5DatasetReader.hpp
test/H5Test.cpp

* Fixes DataArray<bool> converting to DataArray<uint8> when reading from HDF5.
* Added DataStore<bool> alias.
* Added unit test checking HDF5 DataArray type consistency round trip.
* Tests bool array value consistent between reading and writing.
fixes #247

Fixed BoolArray to/from HDF5 changes type

---

.github/workflows/macos.yml

GitHub is deprecating macOS 10.15 (Catalina) in AUG 2022

Update GitHub Actions to use MacOS 11.6 (Big Sur).

---

src/complex/Filter/FilterList.cpp

std::unordered_map.at() will throw exception if the key is not in the map

Ensure the pluginId is available in the unordered_map before using .at()

---

CMakeLists.txt
src/Plugins/ComplexCore/CMakeLists.txt
src/Plugins/ComplexCore/src/ComplexCore/Filters/MoveData.cpp
src/Plugins/ComplexCore/src/ComplexCore/Filters/MoveData.hpp
src/Plugins/ComplexCore/test/CMakeLists.txt
src/Plugins/ComplexCore/test/MoveDataTest.cpp
src/complex/Filter/Actions/MoveDataAction.cpp
src/complex/Filter/Actions/MoveDataAction.hpp

* Added filter, action, and unit test
* Filter moves a DataObject from one parent to another using the DataPath provided for the target DataObject.
* Cannot move to one of the DataObject's existing parents.

Added MoveData filter
